### ISSUE TITLE
1.12.1 Error, Unhandled Exception on Packet Receiving

### ISSUE THREAD

**Issue by MatheweB** [Photon-GitHub/AACAdditionPro#119]
I get the following errors on the new 1.12.1 update. I am on the recommended version of SpigotLib, and the latest spigot 1.12.1, with the lates AAC and AACAdditionPro
```
03.08 11:54:41 [Server] ERROR Parameters: 
03.08 11:54:41 [Server] INFO net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition@a15556d[
03.08 11:54:41 [Server] INFO x=-1923.8389907367864
03.08 11:54:41 [Server] INFO y=69.00613931525189
03.08 11:54:41 [Server] INFO z=218.24838560340717
03.08 11:54:41 [Server] INFO yaw=0.0
03.08 11:54:41 [Server] INFO pitch=0.0
03.08 11:54:41 [Server] INFO f=false
03.08 11:54:41 [Server] INFO hasPos=true
03.08 11:54:41 [Server] INFO hasLook=false
03.08 11:54:41 [Server] INFO ]
03.08 11:54:41 [Server] ERROR [AACAdditionPro] Unhandled exception occured in onPacketReceiving(PacketEvent) for AACAdditionPro
03.08 11:54:41 [Server] INFO java.lang.NullPointerException: null
03.08 11:54:41 [Server] INFO at me.konsolas.iaac.i.getViolationLevel(i.java:12) ~[lib3706200008391269187.tmp:?]
03.08 11:54:41 [Server] INFO at de.photon.AACAdditionPro.c.onPacketReceiving(c.java) ~[AACAdditionPro-3.0.2-b4.jar:?]
03.08 11:54:41 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.3.0]
03.08 11:54:41 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.3.0]
03.08 11:54:41 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.3.0]
03.08 11:54:41 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.3.0]
03.08 11:54:41 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.3.0]
03.08 11:54:41 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.3.0]
03.08 11:54:41 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:531) [ProtocolLib.jar:4.3.0]
03.08 11:54:41 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.0]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
03.08 11:54:41 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [spigot-1.12.jar:git-Spigot-edd0396-2a927e8]
```

**Comment by CeIebrimbor** [comment]
I would be surprised if there _weren't_ issues by updating to unsupported versions.

**Comment by Photon-GitHub** [comment]
This will not be fixed until ProtocolLib reaches a non-dev status of 4.4.0

**Comment by Photon-GitHub** [comment]
Additionally this is some problem of AAC as you can see in the first line of the stacktrace.
