### ISSUE TITLE
Error on the latest version

### ISSUE THREAD

**Issue by Games4k** [Photon-GitHub/AACAdditionPro#136]
```
[15:07:57 ERROR]: Error occurred while enabling AACAdditionPro v3.2.3 (Is it up to date?)
java.lang.NoSuchFieldError: REL_ENTITY_MOVE_LOOK
        at de.photon.AACAdditionPro.bE.a(bE.java) ~[?:?]
        at de.photon.AACAdditionPro.bC.<init>(bC.java) ~[?:?]
        at de.photon.AACAdditionPro.bE.<init>(bE.java) ~[?:?]
        at de.photon.AACAdditionPro.A.<init>(A.java) ~[?:?]
        at de.photon.AACAdditionPro.bL.<init>(bL.java) ~[?:?]
        at de.photon.AACAdditionPro.bL.<clinit>(bL.java) ~[?:?]
        at sun.misc.Unsafe.ensureClassInitialized(Native Method) ~[?:1.8.0_144]
        at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(Unknown Source) ~[?:1.8.0_144]
        at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassValue.getFromHashMap(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassValue.getFromBackup(Unknown Source) ~[?:1.8.0_144]
        at java.lang.ClassValue.get(Unknown Source) ~[?:1.8.0_144]
        at java.lang.invoke.DirectMethodHandle.checkInitialized(Unknown Source) ~[?:1.8.0_144]
        at java.lang.invoke.DirectMethodHandle.ensureInitialized(Unknown Source) ~[?:1.8.0_144]
        at java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(Unknown Source) ~[?:1.8.0_144]
        at de.photon.AACAdditionPro.AACAdditionPro.onEnable(AACAdditionPro.java) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.1.jar:git-Paper-1201]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.1.jar:git-Paper-1201]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.1.jar:git-Paper-1201]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.1.jar:git-Paper-1201]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.1.jar:git-Paper-1201]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.1.jar:git-Paper-1201]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.1.jar:git-Paper-1201]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.1.jar:git-Paper-1201]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [patched_1.12.1.jar:git-Paper-1201]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.1.jar:git-Paper-1201]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by Janmm14** [comment]
Please use the recommended version of ProtocolLib. Your ProtocolLib version is heavily outdated.
