### ISSUE TITLE
Error: KillauraEntity 

### ISSUE THREAD

**Issue by Henriks9** [Photon-GitHub/AACAdditionPro#150]
### Issue description

Error beim KillauraEntity

```
[20:42:10] [Craft Scheduler Thread - 0/WARN]: Exception in thread "Craft Scheduler Thread - 0"
[20:42:10] [Craft Scheduler Thread - 0/WARN]: org.apache.commons.lang.UnhandledException: Plugin AACAdditionPro v3.3.1 generated an exception while executing task 1021
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
at de.photon.AACAdditionPro.J.lambda$null$0(J.java)
at java.util.ArrayList.removeIf(ArrayList.java:1405)
at de.photon.AACAdditionPro.J.lambda$onJoin$2(J.java)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more
```
### Core information

Server version: Spigot 1.8.8

AAC version: AACAdditionPro 3.3.1/AAC 3.3.4-b1

ProtocolLib version: ProtocolLib v4.2.0

Plugin list: AAC/ProtocolLib/ AACAdditionPro

### Special environment information

ViaVersion version: insert NO

ProtocolSupport version: insert (or N/A)

ViaBackwards version: insert (or N/A)

BungeeCord plugins: insert (or N/A)

### Configuration

Please describe any modifications you have made to the default config. You do not need to include information about the "thresholds" section of any check, unless you are reporting a false kick/ban.

For the lazy, you may use this online diff tool - make sure you select "Store forever".

**Comment by Janmm14** [comment]
btw. it is meant that you delete the informative text of the template after reading it.

**Comment by Photon-GitHub** [comment]
Adressed in 3.4.0
