### ISSUE TITLE
Critical error whilst trying to respawn the entity

### ISSUE THREAD

**Issue by mcPr0xy** [Photon-GitHub/AACAdditionPro#153]
Please include:
- Server version: 1.12.2
- ProtocolLib version: latest (dev-build)
- The version of AACAdditionPro: latest (3.4.1)
- A detailed description of the bug / wanted feature: Critical Error when doing the aacadditionpro entitycheck <player> <duration of check in ticks> in console.

`[22:14:30] [Server thread/INFO]: [0;31;22m[AACAdditionPro] [0;31;1mCritical error whilst trying to respawn the entity.[m
[22:14:30] [Server thread/ERROR]: [AACAdditionPro] Critical error whilst trying to respawn the entity.
[22:14:30] [Server thread/WARN]: java.lang.IllegalStateException: Too many repspawn iterations.
[22:14:30] [Server thread/WARN]: 	at de.photon.AACAdditionPro.Z.c(Z.java)
[22:14:30] [Server thread/WARN]: 	at de.photon.AACAdditionPro.Z.lambda$execute$0(Z.java)
[22:14:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
[22:14:30] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
[22:14:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
[22:14:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[22:14:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[22:14:30] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[22:14:30] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`

it seems to happen randomly. Sometimes it works sometimes not.

- If possible a short video of the bug:

**Comment by Photon-GitHub** [comment]
This is the fallback error indicating that your server suffers from heavy load / lag. It is not harmful, but denies the execution of the command.

**Comment by Photon-GitHub** [comment]
Addition: This error will also appear on a test server if only one account has played on the server so far due to the limitations of the system which needs a GameProfile that is not the player himself.
