### ISSUE TITLE
Scoreboard Error

### ISSUE THREAD

**Issue by PatoTheBest** [Photon-GitHub/AACAdditionPro#160]
Please include:
- Server version:
1.11.2
 
- ProtocolLib version:
latest dev build
 
- The version of AACAdditionPro:
3.4.2
 
- A detailed description of the bug / wanted feature: 
Console error spam

- If possible a short video of the bug: 

```
com.destroystokyo.paper.exception.ServerSchedulerException: Task #19755 for AACAdditionPro v3.4.2 generated an exception
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:367)
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829)
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unregistered scoreboard component
        at org.bukkit.craftbukkit.v1_11_R1.scoreboard.CraftTeam.checkState(CraftTeam.java:253)
        at org.bukkit.craftbukkit.v1_11_R1.scoreboard.CraftTeam.removeEntry(CraftTeam.java:155)
        at de.photon.AACAdditionPro.aM.a(aM.java:-1)
        at de.photon.AACAdditionPro.aH.b(aH.java:-1)
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829)
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by PatoTheBest** [comment]
Sorry, duplicate of https://github.com/Photon-GitHub/AACAdditionPro/issues/158
