### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by aggellos2001** [Photon-GitHub/AACAdditionPro#166]
Please include:
- Server version: 
1.8.8
- ProtocolLib version: 
4.3.0
- The version of AACAdditionPro: 
3.4.6
- A detailed description of the bug / wanted feature: 
Basically, I got this error on the console:
`[13:40:35] [Netty Epoll Server IO #2/ERROR]: [AACAdditionPro] Unhandled exception occured in onPacketReceiving(PacketEvent) for AACAdditionPro
java.lang.NullPointerException
at de.photon.AACAdditionPro.b.onPacketReceiving(b.java) ~[AACAdditionPro-3.4.6.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.3.0]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.3.0]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.3.0]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.3.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.3.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.3.0]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:531) [ProtocolLib.jar:4.3.0]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.0]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[13:40:35] [Netty Epoll Server IO #2/ERROR]: Parameters:
net.minecraft.server.v1_8_R3.PacketPlayInHeldItemSlot@2fcb3b18[
itemInHandIndex=7
]
[13:40:35] [Netty Epoll Server IO #2/ERROR]: [AACAdditionPro] Unhandled exception occured in onPacketReceiving(PacketEvent) for AACAdditionPro
java.lang.NullPointerException
at de.photon.AACAdditionPro.b.onPacketReceiving(b.java) ~[AACAdditionPro-3.4.6.jar:?]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.3.0]
at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.3.0]
at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.3.0]
at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.3.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.3.0]
at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.3.0]
at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:531) [ProtocolLib.jar:4.3.0]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib.jar:4.3.0]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [minecraft_server.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[13:40:35] [Netty Epoll Server IO #2/ERROR]: Parameters:
net.minecraft.server.v1_8_R3.PacketPlayInHeldItemSlot@2cce126c[
itemInHandIndex=8
]`
Not sure what's going on but seems like errors with protocol lib.

**Comment by aggellos2001** [comment]
Here is the full error found from logs. I can see aac crashing so maybe that's the case but not sure.
[https://pastebin.com/BK7fRxE2](https://pastebin.com/BK7fRxE2)

**Comment by CeIebrimbor** [comment]
Try this ProtocolLib instead of the version specifically designed for 1.9-1.11 servers (I know that's not advertised, but it's the truth).

http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

**Comment by aggellos2001** [comment]
Alright but my server is 1.8.8. Will that work?

**Comment by CeIebrimbor** [comment]
Yes. If issues still occur, then give [4.2.0](http://ci.dmulloy2.net/job/ProtocolLib/341/) a try. It was built _specifically_ for 1.8.8 and stopped adding compliance for 1.9+.

**Comment by aggellos2001** [comment]
Right thanks!

**Comment by CeIebrimbor** [comment]
Will re-open if you post that the issue is still valid.
