### ISSUE TITLE
Error with teams, java.lang.IllegalArgumentException: Entry cannot be null

### ISSUE THREAD

**Issue by PatoTheBest** [Photon-GitHub/AACAdditionPro#170]
Please include:
- Server version: 
1.11.2

- ProtocolLib version: 
v4.4.0-SNAPSHOT-b390

- The version of AACAdditionPro: 
3.4.6

- A detailed description of the bug / wanted feature: 
```
com.destroystokyo.paper.exception.ServerSchedulerException: Task #287966 for AACAdditionPro v3.4.6 generated an exception
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:367)
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829)
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Entry cannot be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192)
        at org.bukkit.craftbukkit.v1_11_R1.scoreboard.CraftTeam.addEntry(CraftTeam.java:142)
        at de.photon.AACAdditionPro.aH.a(aH.java:-1)
        at de.photon.AACAdditionPro.aM.a(aM.java:-1)
        at de.photon.AACAdditionPro.aH.b(aH.java:-1)
        at de.photon.AACAdditionPro.I.lambda$null$0(I.java:-1)
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:829)
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763)
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by Photon-GitHub** [comment]
Addressed in 3.5.0
