### ISSUE TITLE
Netty Epoll Server IO #2/ERROR

### ISSUE THREAD

**Issue by xXSchrandXx** [Photon-GitHub/AACAdditionPro#187]
Please include:
- Server version: git-Spigot-4bd94dc-e3b4cf5 (MC: 1.12.2)
- ProtocolLib version: 4.4.0-SNAPSHOT-b390
- The version of AACAdditionPro: 3.7.0
- A detailed description of the bug / wanted feature:
`[Netty Epoll Server IO #2/ERROR]: [AACAdditionPro] Unhandled exception occured in onPacketReceiving(PacketEvent) for AACAdditionPro
java.lang.UnsupportedOperationException: The method isSprinting is not supported for temporary players.
	at com.comphenix.protocol.injector.server.TemporaryPlayerFactory$1.intercept(TemporaryPlayerFactory.java:144) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.server.TemporaryPlayer$$EnhancerByCGLIB$$af0ec699.isSprinting(<generated>) ~[?:?]
	at de.photon.AACAdditionPro.f.onPacketReceiving(f.java:8) ~[AACAdditionPro.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:543) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:275) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24) [ProtocolSupport.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39) [ProtocolSupport.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at com.github.games647.lagmonitor.traffic.TinyProtocol$1$1.channelRead(TinyProtocol.java:79) [LagMonitor.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [spigot.jar:git-Spigot-4bd94dc-e3b4cf5]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[20:30:07] [Netty Epoll Server IO #2/ERROR]: Parameters: 
  net.minecraft.server.v1_12_R1.PacketPlayInSettings@706f7407[
    a=de_de
    b=15
    c=FULL
    d=true
    e=78
    f=Right
  ]`

**Comment by Photon-GitHub** [comment]
Problem of ProtocolLib itself, see #183

**Comment by Janmm14** [comment]
Also it doesn't harm.
