### ISSUE TITLE
BlockPlaceEvent ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by FrankHeijden** [Photon-GitHub/AACAdditionPro#188]
```
13.02 00:27:05 [Server] ERROR Could not pass event BlockPlaceEvent to AACAdditionPro v3.8.0
13.02 00:27:05 [Server] INFO org.bukkit.event.EventException: null
13.02 00:27:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:150) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at net.minecraft.server.v1_12_R1.ItemStack.placeItem(ItemStack.java:207) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:505) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:951) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
13.02 00:27:05 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
13.02 00:27:05 [Server] INFO at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
13.02 00:27:05 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
13.02 00:27:05 [Server] INFO at de.photon.AACAdditionPro.aG.a(aG.java:10) ~[AACAdditionPro-3.8.0.jar:?]
13.02 00:27:05 [Server] INFO at de.photon.AACAdditionPro.aG.a(aG.java:11) ~[AACAdditionPro-3.8.0.jar:?]
13.02 00:27:05 [Server] INFO at de.photon.AACAdditionPro.T.a(T.java:8) ~[AACAdditionPro-3.8.0.jar:?]
13.02 00:27:05 [Server] INFO at sun.reflect.GeneratedMethodAccessor373.invoke(Unknown Source) ~[?:?]
13.02 00:27:05 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
13.02 00:27:05 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
13.02 00:27:05 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-update.jar:git-Spigot-4bd94dc-e3b4cf5]
13.02 00:27:05 [Server] INFO ... 18 more
```

Please include:
- Server version: spigot 1.12.2
- ProtocolLib version: 4.4.0
- The version of AACAdditionPro: 3.8.0
- A detailed description of the bug / wanted feature: -
- If possible a short video of the bug: -

**Comment by Photon-GitHub** [comment]
Addressed in 3.8.1
