### ISSUE TITLE
An error occurred when players join the server.

### ISSUE THREAD

**Issue by CraftG** [Photon-GitHub/AACAdditionPro#198]
Please include:
- Server version: PaperSpigot1.11.2
- ProtocolLib version: 4.3.0
- The version of AACAdditionPro: 3.9.1
- A detailed description of the bug / wanted feature: When the player join the game, an error occurs. Error message is as follows:
[AACAdditionPro] Plugin AACAdditionPro v3.9.1 generated an exception while executing task 13706
java.lang.NullPointerException
at de.photon.AACAdditionPro.P.lambda$onJoin$1(P.java:35) ~[?:?]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot1.11.2.jar:git-Paper-1104]
at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [PaperSpigot1.11.2.jar:git-Paper-1104]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [PaperSpigot1.11.2.jar:git-Paper-1104]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_162]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_162]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
- If possible a short video of the bug:

**Comment by Photon-GitHub** [comment]
Please don't write "latest version", but the actual version of AACAdditionPro.

**Comment by Photon-GitHub** [comment]
Also, is this happening on every server join? In that case please include your server logs or dm me them on spigot.

**Comment by Photon-GitHub** [comment]
Please answer my questions, otherwise I will close this due to inactivity.

**Comment by Photon-GitHub** [comment]
Close due to inactivity.
