### ISSUE TITLE
NPE@R.lambda$onJoin$1:45

### ISSUE THREAD

**Issue by Minemaniak** [Photon-GitHub/AACAdditionPro#207]
- Server version: 1.8.8
-Client version: 1.8.9
- ProtocolLib version: 4.2.0
- The version of AACAdditionPro: 3.11.0

```
[00:43:19 INFO]: Lorak_[/xx.xxx.xx.x:51681] logged in with entity id 89 at ([world]570.9139294689526, 4.0, -474.35646525891184)
[00:43:19 WARN]: Exception in thread "Craft Scheduler Thread - 50" 
[00:43:19 WARN]: org.apache.commons.lang.UnhandledException: Plugin AACAdditionPro v3.11.0 generated an exception while executing task 621
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at de.photon.AACAdditionPro.R.lambda$onJoin$1(R.java:45)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by Photon-GitHub** [comment]
Please recheck on 3.12.2 as this might be fixed in the latest version.

**Comment by Minemaniak** [comment]
From what I see, it is fixed, thanks.
