### ISSUE TITLE
Error: Unable to clone object

### ISSUE THREAD

**Issue by MikhailY** [Photon-GitHub/AACAdditionPro#211]
Please include:
- Server version:  paperspigot1.12.2
- ProtocolLib version: 390
- The version of AACAdditionPro: 3.11.1
```
[13:21:14] [Server thread/ERROR]: [AACAdditionPro] Unhandled exception occured in onPacketSending(PacketEvent) for AACAdditionPro
java.lang.RuntimeException: Unable to clone object {NoGravity=1b, AgeLocked=0b, HurtByTimestamp=105298, Sitting=0b, Attributes=[{Base:6.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.20000000298023224d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:16.0d,Modifiers:[{UUIDMost:-6946414310237451730L,UUIDLeast:-9206714278553406288L,Amount:-0.035526684024599915d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"},{Base:0.4000000059604645d,Name:"generic.flyingSpeed"}], Invulnerable=0b, FallFlying=0b, ForcedAge=0, PortalCooldown=0, AbsorptionAmount=0.0f, FallDistance=0.0f, InLove=0, DeathTime=0s, WorldUUIDMost=-8052460099515694284L, HandDropChances=[0.085f,0.085f], PersistenceRequired=1b, id="minecraft:parrot", Spigot.ticksLived=198491, Age=0, Motion=[0.013209014580431545d,0.13143284633198668d,-0.044476091826147306d], Leashed=0b, UUIDLeast=-7046017069163414556L, Health=1.0f, Bukkit.updateLevel=2, LeftHanded=0b, Air=300s, OnGround=0b, Dimension=0, Rotation=[232.45435f,-40.0f], HandItems=[{},{}], Variant=4, ArmorDropChances=[0.085f,0.085f,0.085f,0.085f], OwnerUUID="0d87a1fd-18a9-34c4-ba60-826709c0f24a", UUIDMost=9017694068048675798L, Pos=[-166.71713765997208d,8.428359099606764d,961.3588037309944d], Fire=-1s, ArmorItems=[{},{},{},{}], CanPickUpLoot=0b, HurtTime=0s, WorldUUIDLeast=-7120437945761443436L, Paper.Origin=[1946.5d,68.0d,1684.5d]} (java.util.HashMap)
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:44) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:24) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.CollectionCloner.cloneConstructor(CollectionCloner.java:178) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.CollectionCloner.clone(CollectionCloner.java:76) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:257) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.FieldCloner.defaultTransform(FieldCloner.java:67) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.events.PacketContainer$2$1.access$200(PacketContainer.java:1062) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.events.PacketContainer$2$1$1.transformField(PacketContainer.java:1071) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.ObjectWriter.copyToInternal(ObjectWriter.java:115) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.ObjectWriter.copyTo(ObjectWriter.java:80) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.FieldCloner.clone(FieldCloner.java:91) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:257) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.FieldCloner.defaultTransform(FieldCloner.java:67) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.events.PacketContainer$2$1.access$200(PacketContainer.java:1062) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.events.PacketContainer$2$1$1.transformField(PacketContainer.java:1071) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.ObjectWriter.copyToInternal(ObjectWriter.java:115) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.ObjectWriter.copyTo(ObjectWriter.java:80) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.FieldCloner.clone(FieldCloner.java:91) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:257) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.CollectionCloner.getClone(CollectionCloner.java:130) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.CollectionCloner.clone(CollectionCloner.java:68) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:257) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.FieldCloner.defaultTransform(FieldCloner.java:67) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.events.PacketContainer$2$1.access$200(PacketContainer.java:1062) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.events.PacketContainer$2$1$1.transformField(PacketContainer.java:1071) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.ObjectWriter.copyToInternal(ObjectWriter.java:115) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.ObjectWriter.copyTo(ObjectWriter.java:80) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.FieldCloner.clone(FieldCloner.java:91) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:257) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:1051) ~[ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at de.photon.AACAdditionPro.g.onPacketSending(g.java:25) ~[AACAdditionPro-3.11.1.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:398) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:78) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:364) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:332) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.4.0-SNAPSHOT-b390]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:200) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:148) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1183) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:371) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.EntityTracker.a(EntityTracker.java:264) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.PlayerChunk.sendChunk(PlayerChunk.java:163) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.PlayerChunk.a(PlayerChunk.java:77) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.PlayerChunkMap.addPlayer(PlayerChunkMap.java:311) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:313) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:411) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:183) [craftbukkit2.jar:git-Paper-1383]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:124) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:132) [ProtocolSupport.jar:?]
	at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tick(AbstractLoginListenerPlay.java:94) [ProtocolSupport.jar:?]
	at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.e(SpigotLoginListenerPlay.java:70) [ProtocolSupport.jar:?]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:255) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:941) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [craftbukkit2.jar:git-Paper-1383]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [craftbukkit2.jar:git-Paper-1383]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.io.NotSerializableException: net.minecraft.server.v1_12_R1.NBTTagByte
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[?:1.8.0_161]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_161]
	at java.util.HashMap.internalWriteEntries(HashMap.java:1790) ~[?:1.8.0_161]
	at java.util.HashMap.writeObject(HashMap.java:1363) ~[?:1.8.0_161]
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1128) ~[?:1.8.0_161]
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[?:1.8.0_161]
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_161]
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_161]
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_161]
	at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:40) ~[?:?]
	... 68 more
[13:21:14] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_12_R1.PacketPlayOutEntityMetadata@498be593[
    a=856
    b=[net.minecraft.server.v1_12_R1.DataWatcher$Item@a08a068, net.minecraft.server.v1_12_R1.DataWatcher$Item@55d85e90, net.minecraft.server.v1_12_R1.DataWatcher$Item@1f4d08d8, net.minecraft.server.v1_12_R1.DataWatcher$Item@70184eeb, net.minecraft.server.v1_12_R1.DataWatcher$Item@3f5cbb60, net.minecraft.server.v1_12_R1.DataWatcher$Item@28e75ec5, net.minecraft.server.v1_12_R1.DataWatcher$Item@5f9b98c9, net.minecraft.server.v1_12_R1.DataWatcher$Item@6dc6eac7, net.minecraft.server.v1_12_R1.DataWatcher$Item@371bdba4, net.minecraft.server.v1_12_R1.DataWatcher$Item@2518baf4, net.minecraft.server.v1_12_R1.DataWatcher$Item@26c6334e, net.minecraft.server.v1_12_R1.DataWatcher$Item@7c0c6583, net.minecraft.server.v1_12_R1.DataWatcher$Item@1523475d, net.minecraft.server.v1_12_R1.DataWatcher$Item@750c9017, net.minecraft.server.v1_12_R1.DataWatcher$Item@62c791bb, net.minecraft.server.v1_12_R1.DataWatcher$Item@7d78c01d, net.minecraft.server.v1_12_R1.DataWatcher$Item@726e6940]
  ]
```

**Comment by Photon-GitHub** [comment]
Please use hastebin for stacktraces, otherwise they are basically unreadable.

**Comment by Photon-GitHub** [comment]
Please recheck on the latest version.

**Comment by Photon-GitHub** [comment]
Closed due to inactivity.
