### ISSUE TITLE
error exist

### ISSUE THREAD

**Issue by geumu** [Photon-GitHub/AACAdditionPro#23]
[05:35:00] [Server thread/INFO]: geumu lost connection: Disconnected
[05:35:00] [Server thread/INFO]: geumu left the game
[05:35:03] [User Authenticator #2/INFO]: UUID of player geumu is 713a66e9-8a14-44e1-8ae6-c4c67834e080
[05:35:03] [Netty Server IO #1/ERROR]: [AACAdditionPro] Unhandled exception occured in onPacketReceiving(PacketEvent) for AACAdditionPro
java.lang.NullPointerException: User was not found!
	at de.photon.AACAdditionPro.d.b.a(Unknown Source) ~[AACAdditionPro_1.1.1.jar:?]
	at de.photon.AACAdditionPro.b.b.a.onPacketReceiving(Unknown Source) ~[AACAdditionPro_1.1.1.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.1.0-SNAPSHOT-b318]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.1.0-SNAPSHOT-b318]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.1.0-SNAPSHOT-b318]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.1.0-SNAPSHOT-b318]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.1.0-SNAPSHOT-b318]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.1.0-SNAPSHOT-b318]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.1.0-SNAPSHOT-b318]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-de459a2-51263e9]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.1.0-SNAPSHOT-b318]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [spigot.jar:git-Spigot-de459a2-51263e9]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-de459a2-51263e9]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[05:35:03] [Netty Server IO #1/ERROR]: Parameters: 
  net.minecraft.server.v1_10_R1.PacketPlayInHeldItemSlot@73b73121[
    itemInHandIndex=4
  ]

my spigot is 1.10.2
what can i do?

**Comment by Photon-GitHub** [comment]
This is nothing problematic, it just means that the player logged off while he was checked.
I plan a big update next week as I am ill right now, this will be added to my todos.

Thanks for using the issue tracker instead of just messaging me 😃.

**Comment by CeIebrimbor** [comment]
Well, he asked me and I sent him. I was the filter :P

**Comment by Photon-GitHub** [comment]
Fixed in 1.1.2
