### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by UncleM0** [Photon-GitHub/AACAdditionPro#244]
Please include:
- Server version: 1.12.2 
- ProtocolLib version: 4.3.0
- The version of AACAdditionPro: 3.13.1
- A detailed description of the bug / wanted feature: The console get spammed with an error.
- If possible a short video of the bug: 

 [AACAdditionPro] Task #378305 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.Q.lambda$null$0(Q.java:13) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

[AACAdditionPro] Task #378306 for AACAdditionPro v3.13.1 generated an exception
java.lang.NullPointerException: null
	at de.photon.AACAdditionPro.bn.b(bn.java:121) ~[AACAdditionPro-3.13.1.jar:?]
	at de.photon.AACAdditionPro.bo.b(bo.java:95) ~[AACAdditionPro-3.13.1.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-642f6d2-6103339]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]

08.07 17:43:49 [Server] WARN [AACAdditionPro] Task #378306 for AACAdditionPro v3.13.1 generated an exception
08.07 17:43:49 [Server] INFO java.lang.NullPointerException: null
08.07 17:43:49 [Server] WARN [AACAdditionPro] Task #378306 for AACAdditionPro v3.13.1 generated an exception
08.07 17:43:49 [Server] INFO java.lang.NullPointerException: null
08.07 17:43:49 [Server] WARN [AACAdditionPro] Task #378306 for AACAdditionPro v3.13.1 generated an exception
08.07 17:43:49 [Server] INFO java.lang.NullPointerException: null
08.07 17:43:50 [Server] WARN [AACAdditionPro] Task #378306 for AACAdditionPro v3.13.1 generated an exception
08.07 17:43:50 [Server] INFO java.lang.NullPointerException: null
08.07 17:43:50 [Server] WARN [AACAdditionPro] Task #378306 for AACAdditionPro v3.13.1 generated an exception
 *Edit by Janmm14: Truncated, much more*

**Comment by Photon-GitHub** [comment]
Might be fixed in 4.0.0 due to the huge KillauraEntity changes.
