### ISSUE TITLE
paper spigot spam on console

### ISSUE THREAD

**Issue by leoncp9** [Photon-GitHub/AACAdditionPro#247]
Please include:
- Server version: paper spigot 1.12.2 latest build
- ProtocolLib version: latest
- The version of AACAdditionPro: latest
- A detailed description of the bug / wanted feature: 
[06:01:01] [Server thread/WARN]: [AACAdditionPro] Task #147 for AACAdditionPro v4.0.0 generated an exception
java.lang.UnsupportedOperationException: null
	at com.google.common.collect.ImmutableCollection.removeIf(ImmutableCollection.java:270) ~[Paper-1502.jar:git-Paper-1502]
	at de.photon.AACAdditionPro.bs.a(bs.java:6) ~[?:?]
	at de.photon.AACAdditionPro.bn.b(bn.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[Paper-1502.jar:git-Paper-1502]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) [Paper-1502.jar:git-Paper-1502]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:839) [Paper-1502.jar:git-Paper-1502]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [Paper-1502.jar:git-Paper-1502]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) [Paper-1502.jar:git-Paper-1502]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [Paper-1502.jar:git-Paper-1502]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]

**Comment by Photon-GitHub** [comment]
Closed in favor of #248
