### ISSUE TITLE
Unhandled exception occured in onPacketSending(PacketEvent)

### ISSUE THREAD

**Issue by DaveDevil** [Photon-GitHub/AACAdditionPro#255]
Please include:
- Server version:  git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)
- ProtocolLib version: 4.3.0
- The version of AACAdditionPro: 4.0.2
- A detailed description of the bug / wanted feature: error spamming in console (see down here). This error spams until server crash (very frequently)
- If possible a short video of the bug: 

```
[AACAdditionPro] Unhandled exception occured in onPacketSending(PacketEvent) for AACAdditionPro
java.lang.RuntimeException: Unable to clone object {AgeLocked=0b, HurtByTimestamp=0, Sitting=0b, Attributes=[{Base:6.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.20000000298023224d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:16.0d,Modifiers:[{UUIDMost:-6830380316362651830L,UUIDLeast:-6937722016502839946L,Amount:-0.02044502206341789d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"},{Base:0.4000000059604645d,Name:"generic.flyingSpeed"}], Invulnerable=0b, FallFlying=0b, ForcedAge=0, PortalCooldown=0, AbsorptionAmount=0.0f, FallDistance=0.0f, InLove=0, DeathTime=0s, WorldUUIDMost=-2151544630753671252L, HandDropChances=[0.085f,0.085f], PersistenceRequired=1b, id="minecraft:parrot", Spigot.ticksLived=120240, Age=0, Motion=[0.0d,-0.0784000015258789d,0.0d], Leashed=0b, UUIDLeast=-8114850276433832175L, Health=6.0f, Bukkit.updateLevel=2, LeftHanded=0b, Air=300s, OnGround=1b, Dimension=0, Rotation=[130.8906f,-40.0f], HandItems=[{},{}], Variant=2, ArmorDropChances=[0.085f,0.085f,0.085f,0.085f], OwnerUUID="38347a77-fdbf-3db8-8522-4488f48217a1", UUIDMost=4270899479534977691L, Pos=[-17.75d,148.0d,14.883094294867918d], Fire=-1s, ArmorItems=[{},{},{},{}], CanPickUpLoot=0b, HurtTime=0s, WorldUUIDLeast=-7445322582896579705L} (java.util.HashMap)
    at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:44) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:24) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.CollectionCloner.cloneConstructor(CollectionCloner.java:178) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.CollectionCloner.clone(CollectionCloner.java:76) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:257) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.FieldCloner.defaultTransform(FieldCloner.java:67) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.events.PacketContainer$2$1.access$200(PacketContainer.java:1056) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.events.PacketContainer$2$1$1.transformField(PacketContainer.java:1065) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.ObjectWriter.copyToInternal(ObjectWriter.java:115) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.ObjectWriter.copyTo(ObjectWriter.java:80) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.FieldCloner.clone(FieldCloner.java:91) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:257) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.FieldCloner.defaultTransform(FieldCloner.java:67) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.events.PacketContainer$2$1.access$200(PacketContainer.java:1056) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.events.PacketContainer$2$1$1.transformField(PacketContainer.java:1065) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.ObjectWriter.copyToInternal(ObjectWriter.java:115) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.ObjectWriter.copyTo(ObjectWriter.java:80) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.FieldCloner.clone(FieldCloner.java:91) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:257) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.CollectionCloner.getClone(CollectionCloner.java:130) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.CollectionCloner.clone(CollectionCloner.java:68) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:257) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.NullableCloner.clone(NullableCloner.java:43) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.FieldCloner.defaultTransform(FieldCloner.java:67) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.events.PacketContainer$2$1.access$200(PacketContainer.java:1056) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.events.PacketContainer$2$1$1.transformField(PacketContainer.java:1065) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.ObjectWriter.copyToInternal(ObjectWriter.java:115) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.ObjectWriter.copyTo(ObjectWriter.java:80) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.FieldCloner.clone(FieldCloner.java:91) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.reflect.cloning.AggregateCloner.clone(AggregateCloner.java:257) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.events.PacketContainer.deepClone(PacketContainer.java:1045) ~[ProtocolLib-4.3.0.jar:4.3.0]
    at de.photon.AACAdditionPro.g.onPacketSending(g.java:15) ~[AACAdditionPro-4.0.2.jar:?]
    at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386) [ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352) [ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320) [ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib-4.3.0.jar:4.3.0]
    at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib-4.3.0.jar:4.3.0]
    at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:194) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:143) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1131) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:346) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.EntityTracker.a(EntityTracker.java:261) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.PlayerChunk.sendChunk(PlayerChunk.java:148) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.PlayerChunk.a(PlayerChunk.java:66) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.PlayerChunkMap.movePlayer(PlayerChunkMap.java:361) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.PlayerList.d(PlayerList.java:387) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.io.NotSerializableException: net.minecraft.server.v1_12_R1.NBTTagByte
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[?:1.8.0_161]
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_161]
    at java.util.HashMap.internalWriteEntries(HashMap.java:1790) ~[?:1.8.0_161]
    at java.util.HashMap.writeObject(HashMap.java:1363) ~[?:1.8.0_161]
    at sun.reflect.GeneratedMethodAccessor309.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
    at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1128) ~[?:1.8.0_161]
    at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496) ~[?:1.8.0_161]
    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432) ~[?:1.8.0_161]
    at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[?:1.8.0_161]
    at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_161]
    at com.comphenix.protocol.reflect.cloning.SerializableCloner.clone(SerializableCloner.java:40) ~[?:?]
    ... 67 more
 [Server thread/ERROR]: Parameters:
  net.minecraft.server.v1_12_R1.PacketPlayOutEntityMetadata@adf0cc6[
    a=12733
    b=[net.minecraft.server.v1_12_R1.DataWatcher$Item@12729de0, net.minecraft.server.v1_12_R1.DataWatcher$Item@7e649bfd, net.minecraft.server.v1_12_R1.DataWatcher$Item@5b9145a7, net.minecraft.server.v1_12_R1.DataWatcher$Item@1d6f3ae5, net.minecraft.server.v1_12_R1.DataWatcher$Item@1bf43935, net.minecraft.server.v1_12_R1.DataWatcher$Item@4195f2c5, net.minecraft.server.v1_12_R1.DataWatcher$Item@10782b2d, net.minecraft.server.v1_12_R1.DataWatcher$Item@74a493d5, net.minecraft.server.v1_12_R1.DataWatcher$Item@4e2321e5, net.minecraft.server.v1_12_R1.DataWatcher$Item@204ef13e, net.minecraft.server.v1_12_R1.DataWatcher$Item@713e9759, net.minecraft.server.v1_12_R1.DataWatcher$Item@21d49890, net.minecraft.server.v1_12_R1.DataWatcher$Item@76afa946, net.minecraft.server.v1_12_R1.DataWatcher$Item@213f71ac, net.minecraft.server.v1_12_R1.DataWatcher$Item@243ebe8d, net.minecraft.server.v1_12_R1.DataWatcher$Item@212bb282, net.minecraft.server.v1_12_R1.DataWatcher$Item@2a45ca78]
  ]
```

**Comment by Photon-GitHub** [comment]
Please use a service like pastebin for errors as that stacktrace is pretty much unreadable.

**Comment by Janmm14** [comment]
@Photon-GitHub It was just wrong markup formating, fixed it. (one ` instead of three cauaing one-line code formatting instead of multiline codeblock

**Comment by Photon-GitHub** [comment]
Still please recheck on the latest version.

**Comment by Photon-GitHub** [comment]
Closed due to inactivity.
