### ISSUE TITLE
IllegalArgumentException: Cannot measure distance between worlds

### ISSUE THREAD

**Issue by Marcobagastruz** [Photon-GitHub/AACAdditionPro#280]
Please include:
- Server version:  1.8.8 PaperSpigot
- ProtocolLib version:  #403 for MC 1.8 thru 1.12.x
- The version of AACAdditionPro:  4.3.0
- A detailed description of the bug / wanted feature: 
error:
[15:21:28] [Server thread/WARN]: [AACAdditionPro] Task #623 for AACAdditionPro v4.3.0 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between Hub and Dwarven
	at org.bukkit.Location.distanceSquared(Location.java:456) ~[SkyWars.jar:git-Spigot-21fe707-e1ebe52]
	at de.photon.AACAdditionPro.aX.a(aX.java:8) ~[?:?]
	at de.photon.AACAdditionPro.aO.b(aO.java:93) ~[?:?]
	at de.photon.AACAdditionPro.aQ.b(aQ.java:34) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[SkyWars.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [SkyWars.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [SkyWars.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [SkyWars.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [SkyWars.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [SkyWars.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
- If possible a short video of the bug: 
Console are spamming this error.

**Comment by Photon-GitHub** [comment]
Please do not use checks which are explicitly marked as experimental / in beta, such as KillauraEntity (the check which causes your error).
Using such checks will, obviously, greatly increase your chances of encountering errors or bugs.

**Comment by Photon-GitHub** [comment]
You should just disable KillauraEntity, especially on a productive server @Marcobagastruz

**Comment by Marcobagastruz** [comment]
Thanks, 
I understand but if i disable it on my server killaura bypass is very easy.
Please if u have time fix it :D
