### ISSUE TITLE
Asynchronous Async Chunk Load Crash

### ISSUE THREAD

**Issue by DankPrison** [Photon-GitHub/AACAdditionPro#288]
Please include:
- Server version: Latest Paper Spigot 1.12.2
- ProtocolLib version: 4.40
- The version of AACAdditionPro: 4.5.0
- A detailed description of the bug / wanted feature: 
My server randomly crashed with this error. I'm assuming it has to do with AACAdditionPro as it's in the error.
```
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:54)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:170)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:153)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:149)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:181)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:118)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:193)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:201)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:197)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:138)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at de.photon.AACAdditionPro.bf.a(bf.java:26)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at de.photon.AACAdditionPro.modules.Q.a(Q.java:120)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at de.photon.AACAdditionPro.modules.Q.lambda$null$0(Q.java:81)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[03:34:09] [ForkJoinPool-1725723-worker-4/WARN]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by Photon-GitHub** [comment]
It is caused by the ESP module, so disable it if needed. Does this only happen after teleports / world changes?

**Comment by DankPrison** [comment]
Not entirely sure. All I know is that it was pretty random... Would have like 20+ people on my server and everything perfect and then server would just straight crash randomly. I've reverted to use 4.4.0 until issue is resolved.

**Comment by Photon-GitHub** [comment]
@DankPrison Reverting to that version will not help you as the code which causes the crash has not changed there. I advise you to stay on latest and just disable ESP.

**Comment by DankPrison** [comment]
@Photon-GitHub I have not had any crashes on 4.4.0 and I've used it for weeks.

**Comment by Photon-GitHub** [comment]
@DankPrison Please tag me if you still have crashes/errors and I will reopen this issue.
