### ISSUE TITLE
EntityDamageByEntity event error, (crashed server)

### ISSUE THREAD

**Issue by KrizzDawg** [Photon-GitHub/AACAdditionPro#290]
Please include:
- Server version: 1.8.8 paperspigot / taco
- ProtocolLib version:  4.4.0-SNAPSHOT-b403
- The version of AACAdditionPro: 4.5.0
- A detailed description of the bug / wanted feature (Down below): 
- If possible a short video of the bug: Not available.

My server crashed with this error, this error was spamming when the EntityDamageByEntity event was cancelled by worldguard.

```
[00:02:39] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AACAdditionPro v4.5.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BeerSpigot.jar:git-TacoSpigot-bf023c7d]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:508) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:493) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:594) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:507) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
    at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:626) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
    at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1160) [BeerSpigot.jar:git-TacoSpigot-bf023c7d]
```

**Comment by Photon-GitHub** [comment]
First of all I do not know how BeerSpigot handles this thing? Does it also appear on plain spigot / paper ? 
Secondly I doubt that this is the whole error. Can you please share a full server log (if you don't want to share it publicly please dm me on spigot or discord)?

**Comment by KrizzDawg** [comment]
Whats your discord

**Comment by Photon-GitHub** [comment]
Photon#4667. Make sure to join the AAC discord to be able to message me.

**Comment by La-Boba** [comment]
Beerspigot has some movement and pvp organizations, but this primarily focus for factions and cannoning. I dont assume that it changes much in the way that would cause this error.

**Comment by Photon-GitHub** [comment]
Closed due to inactivity (I have not received the full log to my knowledge).
