### ISSUE TITLE
The Error

### ISSUE THREAD

**Issue by BackSam6348** [Photon-GitHub/AACAdditionPro#314]
When I open the box, I get an error message like this.

I'm used bukkit Version git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
ProtocolLib Version : 4.4.0
ViaVersion : 2.0.0-SNAPSHOT

[18:58:02 ERROR]: Could not pass event PlayerInteractEvent to AACAdditionPro v5.1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:247) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:768) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:727) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:661) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoSuchMethodError: org.bukkit.World.getNearbyEntities(Lorg/bukkit/Location;DDDLjava/util/function/Predicate;)Ljava/util/Collection;
        at de.photon.AACAdditionPro.user.data.InventoryData$InventoryDataUpdater.onInteract(InventoryData.java:148) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-e4d4710-e1ebe52]
        ... 17 more

**Comment by BackSam6348** [comment]
And more Error
[22:37:32] [Server thread/INFO]: [AACAdditionPro] Enabling AACAdditionPro v5.1.0
[22:37:32] [Server thread/ERROR]: [AACAdditionPro] Loading failed:
[22:37:32] [Server thread/WARN]: java.lang.NullPointerException: Severe loading error: Config-Section is null when loading: KeepAlive.thresholds
[22:37:32] [Server thread/WARN]: 	at java.util.Objects.requireNonNull(Unknown Source)
[22:37:32] [Server thread/WARN]: 	at de.photon.AACAdditionPro.util.files.configs.ConfigUtils.loadKeys(ConfigUtils.java:150)
[22:37:32] [Server thread/WARN]: 	at de.photon.AACAdditionPro.util.violationlevels.Threshold.loadThresholds(Threshold.java:39)
[22:37:32] [Server thread/WARN]: 	at de.photon.AACAdditionPro.util.violationlevels.ViolationLevelManagement.<init>(ViolationLevelManagement.java:53)
[22:37:32] [Server thread/WARN]: 	at de.photon.AACAdditionPro.modules.checks.keepalive.KeepAlive.<init>(KeepAlive.java:26)
[22:37:32] [Server thread/WARN]: 	at de.photon.AACAdditionPro.AACAdditionPro.onEnable(AACAdditionPro.java:180)
[22:37:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[22:37:32] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[22:37:32] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[22:37:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[22:37:32] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[22:37:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:421)
[22:37:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:385)
[22:37:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337)
[22:37:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:264)
[22:37:32] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:532)
[22:37:32] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by Photon-GitHub** [comment]
The second error is caused because you have messed up your config.
