### ISSUE TITLE
1.8 NoSuchMethodError

### ISSUE THREAD

**Issue by UnioDex** [Photon-GitHub/AACAdditionPro#318]
```
[14:56:13 ERROR]: Could not pass event PlayerInteractEvent to AACAdditionPro v5.1.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"312eb2f8"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched.jar:git-TacoSpigot-"312eb2f8"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"312eb2f8"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:750) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [patched.jar:git-TacoSpigot-"312eb2f8"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.Block.isPassable()Z
        at de.photon.AACAdditionPro.user.data.InventoryData$InventoryDataUpdater.onInteract(InventoryData.java:138) ~[AACAdditionPro.jar:?]
        at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"312eb2f8"]

```

AACAP: 5.1.1
Spigot: TacoSpigot 1.8.8

**Comment by Photon-GitHub** [comment]
Will be fixed in 5.1.2.
