### ISSUE TITLE
java.lang.NullPointerException: null KillAuraEntity

### ISSUE THREAD

**Issue by xYukichi** [Photon-GitHub/AACAdditionPro#321]
I run my server on Minecraft 1.12.2
I put the KillAuraEntity on true and was testing with KillAura on my server.
Im using the most recent version of basically everything.
The error:
`[17:41:29 WARN]: [AACAdditionPro] Task #1374 for AACAdditionPro v5.1.1 generated an exception
java.lang.NullPointerException: null
        at de.photon.AACAdditionPro.util.fakeentity.ClientsideLivingEntity.tick(ClientsideLivingEntity.java:134) ~[?:?]
        at de.photon.AACAdditionPro.util.fakeentity.ClientsidePlayerEntity.tick(ClientsidePlayerEntity.java:110) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
`

**Comment by xYukichi** [comment]
With most recent I mean for this version of my server

**Comment by xYukichi** [comment]
https://hastebin.com/ahusahizih.css
&
`[16:46:28 WARN]: [AACAdditionPro] Task #10288 for AACAdditionPro v5.1.2 generated an exception
java.lang.NullPointerException: null
        at de.photon.AACAdditionPro.util.fakeentity.ClientsideLivingEntity.tick(ClientsideLivingEntity.java:134) ~[?:?]
        at de.photon.AACAdditionPro.util.fakeentity.ClientsidePlayerEntity.tick(ClientsidePlayerEntity.java:110) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]`
Are getting spammed in my console right now.

**Comment by Photon-GitHub** [comment]
Do you use the API to change the movement? 
The error should not appear regularily as the movement is always set on construction of the entity.
