### ISSUE TITLE
Task #138903 for AACAdditionPro v5.2.1

### ISSUE THREAD

**Issue by augesrob** [Photon-GitHub/AACAdditionPro#344]
**Plugin Version:** AACAdditionPro 5.2.1
**Minecraft Version:** git-Paper-159 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
**Plugins (63):** AAC, AACAdditionPro, BannerBoard*, BossShopPro, ChestCleaner, Citizens, CommandNPC*, CrateReloaded, DeluxeChat, DeluxeCommands, DeluxeTags*, DiscordBotAPI*, DiscordChatWM, EH-AutoSmelter, EH-MobHoppers, EnjinMinecraftPlugin, EpicFarming, EpicFurnaces, EpicHeads, EpicHoppers, EpicLevels, EpicSpawners, Essentials, EssentialsAntiBuild, EssentialsProtect, EssentialsSpawn, ezAuctions, FabledSkyBlock, HolographicDisplays, HolographicDisplaysExtension*, LiteBans, LuckPerms, MessageAnnouncer, Minions*, MOTDgdCommandAd*, Multiverse-Core, MVdWPlaceholderAPI*, NerfPhantoms, NetworkCore, PlaceholderAPI*, PluginLibrary*, ProtocolLib, Quests*, React*, ServerListPlus, ShopGUIPlus, SpaceSellWands*, SuperbVote, TitleManager*, TokenEnchant, TradeSystem, UltimateCatcher, UltimateFishing, UltimateKits, UltimateTickets*, UltimateTimber, Vault, VoidGenerator, VoteParty, Votifier, WorldEdit, WorldGuard, XLRewards

**Console:**
`>.... [05:19:00 WARN]: [AACAdditionPro] Task #138903 for AACAdditionPro v5.2.1 generated an exception
java.lang.IllegalArgumentException: Unable to find method scanPlayers ([]) in class net.minecraft.server.v1_14_R1.EntityTrackerEntry.
at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:87) ~[?:?]
at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:86) ~[?:?]
at com.comphenix.protocol.reflect.ExactReflection.getMethod(ExactReflection.java:70) ~[?:?]
at com.comphenix.protocol.reflect.accessors.Accessors.getMethodAccessor(Accessors.java:243) ~[?:?]
at com.comphenix.protocol.injector.EntityUtilities.updateEntity(EntityUtilities.java:78) ~[?:?]
at com.comphenix.protocol.injector.PacketFilterManager.updateEntity(PacketFilterManager.java:927) ~[?:?]
at de.photon.AACAdditionPro.util.visibility.PlayerInformationModifier.unModifyInformation(PlayerInformationModifier.java:166) ~[?:?]
at de.photon.AACAdditionPro.modules.checks.Esp.lambda$updateHideMode$2(Esp.java:335) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-159]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-159]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1147) ~[patched_1.14.4.jar:git-Paper-159]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-159]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-159]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-159]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]`

**Comment by Photon-GitHub** [comment]
This is likely a ProtocolLib error as I only call updateEntity. 
Please report this on the ProtocolLib issue tracker.
