### ISSUE TITLE
Task #1188 generated an exemption

### ISSUE THREAD

**Issue by FrankHeijden** [Photon-GitHub/AACAdditionPro#36]
Hello,
My console is spamming this;
[Server] WARN Task #1188 for AACAdditionPro v1.4.2 generated an exception
I do not know why :P

**Comment by Photon-GitHub** [comment]
Please add some more information:
Server version
Protocollib version
Stacktrace
and other stuff that might be important to know.

**Comment by FrankHeijden** [comment]
Spigot 1.11.2-R0.1-SNAPSHOT
Protocollib 4.2.1-SNAPSHOT-b347

Console error:

[08:45:43] [Server thread/WARN]: [AACAdditionPro] Task #1188 for AACAdditionPro v1.4.2 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world
	at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot-os7.jar:git-Spigot-7d78b81-a867313]
	at de.photon.AACAdditionPro.b.a.d.e(Unknown Source) ~[?:?]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-os7.jar:git-Spigot-7d78b81-a867313]
	at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-os7.jar:git-Spigot-7d78b81-a867313]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-os7.jar:git-Spigot-7d78b81-a867313]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-os7.jar:git-Spigot-7d78b81-a867313]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-os7.jar:git-Spigot-7d78b81-a867313]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-os7.jar:git-Spigot-7d78b81-a867313]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

//Edit: it works for now, no errors in console atm.

**Comment by Photon-GitHub** [comment]
Thank you for the report, this will be fixed in 1.5

**Comment by FrankHeijden** [comment]
Another bug, the same as before, but then #1191

console;
18.03 22:00:58 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
18.03 22:00:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-os7.jar:git-Spigot-7d78b81-a867313]
18.03 22:00:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-os7.jar:git-Spigot-7d78b81-a867313]
18.03 22:00:58 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-os7.jar:git-Spigot-7d78b81-a867313]
18.03 22:00:58 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730) [spigot-os7.jar:git-Spigot-7d78b81-a867313]
18.03 22:00:58 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-os7.jar:git-Spigot-7d78b81-a867313]
18.03 22:00:58 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-os7.jar:git-Spigot-7d78b81-a867313]
18.03 22:00:58 [Server] INFO at de.photon.AACAdditionPro.b.a.d.e(Unknown Source) ~[?:?]
18.03 22:00:58 [Server] INFO at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot-os7.jar:git-Spigot-7d78b81-a867313]
18.03 22:00:58 [Server] INFO java.lang.IllegalArgumentException: Cannot measure distance between lobby and world
18.03 22:00:58 [Server] WARN Task #1191 for AACAdditionPro v1.4.2 generated an exception

Also, my players are experiencing some weird animations when theyre not moving at all in gamemode survival. It's shaking weirdly. Don't have any console output for that one. Also sometimes they're getting kicked/warned by AAC for speed when walking/jumping at the same time.

**Comment by Photon-GitHub** [comment]
The error is the same as above and will be fixed in 1.5.
The animation is caused as a side effect by the teleport of the freecam check; if you don't like it just disable freecam.

**Comment by Photon-GitHub** [comment]
Fixed in 1.5
