### ISSUE TITLE
some error, rename this

### ISSUE THREAD

**Issue by untuned** [Photon-GitHub/AACAdditionPro#376]
Got kicked with the message "Disconnected", and another player around me got kicked as well.

```
[19:06:17] [Netty Server IO #1/ERROR]: [AACAdditionPro] Unable to complete the EqualRotation calculations.
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftFuture.get(CraftFuture.java:73) ~[patched_1.15.2.jar:git-Paper-87]
	at de.photon.aacadditionpro.modules.checks.packetanalysis.EqualRotationPattern.process(EqualRotationPattern.java:101) ~[?:?]
	at de.photon.aacadditionpro.modules.checks.packetanalysis.EqualRotationPattern.process(EqualRotationPattern.java:34) ~[?:?]
	at de.photon.aacadditionpro.modules.PatternModule$PacketPattern.apply(PatternModule.java:119) ~[?:?]
	at de.photon.aacadditionpro.modules.checks.packetanalysis.PacketAnalysis.onPacketReceiving(PacketAnalysis.java:81) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) ~[?:?]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) ~[?:?]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:533) ~[?:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-87]
	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:259) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-87]
	at protocolsupport.protocol.packet.PacketDataCodec.read0(PacketDataCodec.java:129) ~[?:?]
	at protocolsupport.protocol.packet.PacketDataCodec$ServerBoundPacketDataProcessor.read(PacketDataCodec.java:206) ~[?:?]
	at protocolsupport.protocol.packet.PacketDataCodec$ServerBoundPacketDataProcessor.process(PacketDataCodec.java:215) ~[?:?]
	at protocolsupport.protocol.packet.PacketDataCodec.read(PacketDataCodec.java:83) ~[?:?]
	at protocolsupport.protocol.packet.middle.serverbound.play.MiddleMoveLook.writeToServer(MiddleMoveLook.java:23) ~[?:?]
	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractPacketDecoder.decodeAndTransform(AbstractPacketDecoder.java:37) ~[?:?]
	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:20) ~[?:?]
	at protocolsupport.protocol.pipeline.version.util.decoder.AbstractModernPacketDecoder.channelRead0(AbstractModernPacketDecoder.java:8) ~[?:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) ~[patched_1.15.2.jar:git-Paper-87]
	at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-87]
	at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:43) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) ~[patched_1.15.2.jar:git-Paper-87]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[patched_1.15.2.jar:git-Paper-87]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
	at de.photon.aacadditionpro.modules.checks.packetanalysis.EqualRotationPattern.lambda$process$0(EqualRotationPattern.java:90) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftFuture.run(CraftFuture.java:88) ~[patched_1.15.2.jar:git-Paper-87]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-87]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-87]
	... 1 more
```

**Comment by Photon-GitHub** [comment]
This means that your server was unable to complete the EqualRotation hitbox calculations which must be handled synchronously. Such an error hints at insufficient server performance and you should probably upgrade your server. Do you have any additional information?

**Comment by Photon-GitHub** [comment]
Closed as of inactivity.
