### ISSUE TITLE
Error with new world

### ISSUE THREAD

**Issue by AceTheGmodGeek** [Photon-GitHub/AACAdditionPro#38]
I made a new world and I seem to be getting:

[19:29:37] [Server thread/WARN]: [AACAdditionPro] Task #1229 for AACAdditionPro v1.4.2 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and BekirsKingdom
    at org.bukkit.Location.distanceSquared(Location.java:456) ~[minecraft_server.jar:git-PaperSpigot-88826e0-9cd1111]
    at de.photon.AACAdditionPro.b.a.d.e(Unknown Source) ~[?:?]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[minecraft_server.jar:git-PaperSpigot-88826e0-9cd1111]
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [minecraft_server.jar:git-PaperSpigot-88826e0-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:779) [minecraft_server.jar:git-PaperSpigot-88826e0-9cd1111]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [minecraft_server.jar:git-PaperSpigot-88826e0-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [minecraft_server.jar:git-PaperSpigot-88826e0-9cd1111]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [minecraft_server.jar:git-PaperSpigot-88826e0-9cd1111]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by Photon-GitHub** [comment]
#36
