### ISSUE TITLE
NPE on connect

### ISSUE THREAD

**Issue by SlimeDog** [Photon-GitHub/AACAdditionPro#386]
Spigot 1.15.2
AACAdditionPro 6.1.0
AAC 4.3.8

Five of these in a row, when OP player connected. This has not happened before. I will try to reproduce.
```
[15:54:28] [ForkJoinPool-132618-worker-3/WARN]: Exception in thread "ForkJoinPool-132618-worker-3" 
[15:54:28] [ForkJoinPool-132618-worker-3/WARN]: java.lang.NullPointerException
[15:54:28] [ForkJoinPool-132618-worker-3/WARN]: 	at de.photon.aacadditionpro.InternalPermission.hasPermission(InternalPermission.java:44)
[15:54:28] [ForkJoinPool-132618-worker-3/WARN]: 	at de.photon.aacadditionpro.user.User.isBypassed(User.java:57)
[15:54:28] [ForkJoinPool-132618-worker-3/WARN]: 	at de.photon.aacadditionpro.modules.checks.Esp.canSee(Esp.java:193)
[15:54:28] [ForkJoinPool-132618-worker-3/WARN]: 	at de.photon.aacadditionpro.modules.checks.Esp.lambda$null$0(Esp.java:158)
[15:54:28] [ForkJoinPool-132618-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
[15:54:28] [ForkJoinPool-132618-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[15:54:28] [ForkJoinPool-132618-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[15:54:28] [ForkJoinPool-132618-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[15:54:28] [ForkJoinPool-132618-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[15:54:28] [ForkJoinPool-132618-worker-3/WARN]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[15:54:28] [ForkJoinPool-132619-worker-3/WARN]: Exception in thread "ForkJoinPool-132619-worker-3"
```

**Comment by Photon-GitHub** [comment]
Can you reproduce this consistently? If yes, could you please add a video of what the player sees ingame?

**Comment by SlimeDog** [comment]
I have not been able to reproduce. :(

**Comment by Photon-GitHub** [comment]
In that case I will label this as "extremely unlucky login", as the NPE happened during permission checking, which implies that AACAdditionPro thinks the player doesn't yet exist.

If this happens more often please reply with a tag to reopen.
