### ISSUE TITLE
Error 1.12.2

### ISSUE THREAD

**Issue by DenisJ9798** [Photon-GitHub/AACAdditionPro#389]
[01:31:04] [Server thread/INFO]: [AACAdditionPro] Enabling AACAdditionPro v6.1.0
[01:31:04] [Server thread/ERROR]: [AACAdditionPro] Loading failed:

java.lang.NullPointerException: Severe loading error: Config-Section is null when loading: AutoEat.thresholds
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_221]
	at de.photon.aacadditionpro.util.files.configs.ConfigUtils.loadKeys(ConfigUtils.java:147) ~[?:?]
	at de.photon.aacadditionpro.util.violationlevels.Threshold.loadThresholds(Threshold.java:39) ~[?:?]
	at de.photon.aacadditionpro.util.violationlevels.ViolationLevelManagement.<init>(ViolationLevelManagement.java:62) ~[?:?]
	at de.photon.aacadditionpro.modules.checks.AutoEat.<init>(AutoEat.java:19) ~[?:?]
	at de.photon.aacadditionpro.AACAdditionPro.onEnable(AACAdditionPro.java:153) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) ~[patched_1.12.2.jar:git-Paper-1613]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[patched_1.12.2.jar:git-Paper-1613]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[patched_1.12.2.jar:git-Paper-1613]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]

**Comment by Janmm14** [comment]
> Config-Section is null when loading: AutoEat.thresholds

**Comment by Photon-GitHub** [comment]
You have misconfigured AACAdditionPro, please regenerate your config.
