### ISSUE TITLE
Error While Enabling

### ISSUE THREAD

**Issue by DrizzyYT** [Photon-GitHub/AACAdditionPro#401]
> I tried removing the plugins that would interfere
 Tried to restart the server
Tried to redownload it
Tried to delete the config and renew it

[02:36:19 ERROR]: Error occurred while enabling AACAdditionPro v6.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com.comphenix.protocol.wrappers.MinecraftKey
at java.lang.ClassLoader.defineClassImpl(Native Method) ~[?:1.8.0_232]
at java.lang.ClassLoader.defineClassInternal(Unknown Source) ~[?:1.8.0_232]
at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_232]
at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_232]
at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_232]
at java.net.URLClassLoader.access$400(Unknown Source) ~[?:1.8.0_232]
at java.net.URLClassLoader$ClassFinder.run(Unknown Source) ~[?:1.8.0_232]
at java.security.AccessController.doPrivileged(Unknown Source) ~[?:1.8.0_232]
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_232]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:193) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:98) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.ClassLoader.loadClassHelper(Unknown Source) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_232]
at de.photon.aacadditionpro.modules.clientcontrol.BetterSprintingControl.<clinit>(BetterSprintingControl.java:31) ~[?:?]
at de.photon.aacadditionpro.AACAdditionPro.onEnable(AACAdditionPro.java:153) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.wrappers.MinecraftKey
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_232]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched.jar:git-PaperSpigot-"4c7641d"]
at java.lang.ClassLoader.loadClassHelper(Unknown Source) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_232]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_232]
... 29 more

**Comment by Janmm14** [comment]
Update ProtocolLib

**Comment by Photon-GitHub** [comment]
As Janmm14 has already pointed out, please update ProtocolLib.
