### ISSUE TITLE
Error When Starting up

### ISSUE THREAD

**Issue by ShreyasAyyengar** [Photon-GitHub/AACAdditionPro#414]
Spigot Version / Build :

ViaVersion:  3.1.1
PLib:  4.6.0-SNAPSHOT-b480

AAC Version: 4.4.1
AACAP: 6.4.0 (Not bought, complied to add features and improve code)

Error on Startup:

`[11:22:40] [Server thread/ERROR]: Error occurred while enabling AACAdditionPro v6.4.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at de.photon.aacadditionpro.AACAdditionPro.onEnable(AACAdditionPro.java:152) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-988b411-055870c]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot.jar:git-Spigot-988b411-055870c]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:git-Spigot-988b411-055870c]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:494) ~[spigot.jar:git-Spigot-988b411-055870c]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:408) ~[spigot.jar:git-Spigot-988b411-055870c]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:435) ~[spigot.jar:git-Spigot-988b411-055870c]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:216) ~[spigot.jar:git-Spigot-988b411-055870c]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot.jar:git-Spigot-988b411-055870c]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot.jar:git-Spigot-988b411-055870c]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
	at org.bstats.bukkit.Metrics.<clinit>(Metrics.java:42) ~[?:?]
	... 11 more
`

**Comment by Janmm14** [comment]
You have to build the plugin using maven.
