### ISSUE TITLE
aacapd error code spamms in the console version: 7.0.0.

### ISSUE THREAD

**Issue by Minecraftsgp** [Photon-GitHub/AACAdditionPro#446]
[19:00:32] [Craft Scheduler Thread - 87/WARN]: [AACAdditionPro] Plugin AACAdditionPro v7.0.0 generated an exception while executing task 119
java.lang.NoSuchMethodError: 'int org.bukkit.entity.Player.getPing()'
    at de.photon.aacadditionpro.util.server.PingProvider.getPing(PingProvider.java:52) ~[?:?]
    at de.photon.aacadditionpro.modules.checks.pingspoof.Pingspoof.lambda$enable$0(Pingspoof.java:73) ~[?:?]
    at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[craftbukkit.jar:2991-Spigot-018b9a0-f3f3094]
    at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [craftbukkit.jar:2991-Spigot-018b9a0-f3f3094]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
    at java.lang.Thread.run(Thread.java:829) [?:?]
this error code come every time
aaapd 7.0.0.0

**Comment by KolakZ** [comment]
Try using `AACAdditionPro 7.0.2` and see if it gets fixed.

**Comment by Gerrygames** [comment]
Update Spigot to the latest 1.16.5 build.

**Comment by Photon-GitHub** [comment]
This is not an error of AACAdditionPro. Please update your Spigot to the latest version and the error will be fixed @Minecraftsgp
