### ISSUE TITLE
Error occurred while enabling AACAdditionPro v7.0.4

### ISSUE THREAD

**Issue by KolakZ** [Photon-GitHub/AACAdditionPro#456]
I am getting the following error on startup when using `AACAdditionPro` for `1.8.8`:
https://gist.github.com/KolakZ/1499fa29548025ef8683d87eea1bf81d

**Comment by Janmm14** [comment]
You need ViaVersion 4 for AACAdditionPro 7

**Comment by KolakZ** [comment]
Alright.

**Comment by KolakZ** [comment]
It's not working with `AACAdditionPro 6` either:
```[20:58:41 ERROR]: [AACAdditionPro] Unhandled exception number 512 occured in onPacketReceiving(PacketEvent) for AACAdditionPro
java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketEvent.isPlayerTemporary()Z
        at de.photon.aacadditionpro.user.UserManager.safeGetUserFromPacketEvent(UserManager.java:35) ~[AACAdditionPro-6.5.3.jar:?]
        at de.photon.aacadditionpro.user.DataUpdaterEvents$VelocityChangeDataUpdater.onPacketReceiving(DataUpdaterEvents.java:304) ~[AACAdditionPro-6.5.3.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.2.0]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.2.0]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
        at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.2.0]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [patched.jar:git-PaperSpigot-"4c7641d"]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]```

**Comment by Janmm14** [comment]
> 
> 
> It's not working with `AACAdditionPro 6` either:
> 
> ```
> java.lang.NoSuchMethodError: com.comphenix.protocol.events.PacketEvent.isPlayerTemporary()Z
>         at de.photon.aacadditionpro.user.UserManager.safeGetUserFromPacketEvent(UserManager.java:35) ~[AACAdditionPro-6.5.3.jar:?]
>         at de.photon.aacadditionpro.user.DataUpdaterEvents$VelocityChangeDataUpdater.onPacketReceiving(DataUpdaterEvents.java:304) ~[AACAdditionPro-6.5.3.jar:?]
>         at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.2.0]
>         at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.2.0]
>         at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610) [ProtocolLib.jar:4.2.0]
>         at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577) [ProtocolLib.jar:4.2.0]
>         at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323) [ProtocolLib.jar:4.2.0]
>         at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288) [ProtocolLib.jar:4.2.0]
>         at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541) [ProtocolLib.jar:4.2.0]
>         at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273) [ProtocolLib.jar:4.2.0]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [patched.jar:git-PaperSpigot-"4c7641d"]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]```
> ```

Too old ProtocolLib, at best update it to 4.6.1

**Comment by KolakZ** [comment]
Alright.

**Comment by Photon-GitHub** [comment]
As Jan has already said, this is fixed by updating ProtocolLib.
