### ISSUE TITLE
Ping Stacktraces

### ISSUE THREAD

**Issue by haloflooder** [Photon-GitHub/AACAdditionPro#468]
Server: 1.16.5 PurPur
AAC: 5.1.0
AACAP: 7.1.1
ProtocolLib: 4.6.0
Config: https://pastebin.com/wHXLhnNV

Been getting these in console after I've updated to the latest version of AAC and AACAdditionPro

```
[11:13:10 WARN]: [AACAdditionPro] Plugin AACAdditionPro v7.1.1 generated an exception while executing task 74
java.lang.NoSuchMethodError: 'int org.bukkit.entity.Player.getPing()'
        at de.photon.aacadditionpro.util.server.ping.ModernPingProvider.getPing(ModernPingProvider.java:9) ~[?:?]
        at de.photon.aacadditionpro.modules.checks.pingspoof.Pingspoof.lambda$enable$0(Pingspoof.java:68) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1053]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1053]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1053]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

This has been spammed in console every once in a while
```
[11:10:38 ERROR]: Could not pass event ViolationEvent to AACAdditionPro v7.1.1
java.lang.NoSuchMethodError: 'int org.bukkit.entity.Player.getPing()'
        at de.photon.aacadditionpro.util.server.ping.ModernPingProvider.getPing(ModernPingProvider.java:9) ~[?:?]
        at de.photon.aacadditionpro.util.execute.Placeholders$PlayerPlaceholders.lambda$static$1(Placeholders.java:109) ~[?:?]
        at de.photon.aacadditionpro.util.execute.Placeholders$PlayerPlaceholders.getReplacement(Placeholders.java:115) ~[?:?]
        at de.photon.aacadditionpro.util.execute.Placeholders.replacePlaceholders(Placeholders.java:65) ~[?:?]
        at de.photon.aacadditionpro.util.messaging.DebugSender.onAdditionViolation(DebugSender.java:85) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor165.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Purpur-1053]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Purpur-1053]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Purpur-1053]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Purpur-1053]
        at de.photon.aacadditionpro.events.ModulePlayerEvent.call(ModulePlayerEvent.java:40) ~[?:?]
        at de.photon.aacadditionpro.util.violationlevels.ViolationLevelManagement.flag(ViolationLevelManagement.java:33) ~[?:?]
        at de.photon.aacadditionpro.modules.checks.inventory.InventoryMove$InventoryMoveAdapter.onPacketReceiving(InventoryMove.java:156) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:537) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:509) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:348) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:594) ~[?:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Purpur-1053]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:290) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.16.5.jar:git-Purpur-1053]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.16.5.jar:git-Purpur-1053]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Janmm14** [comment]
Update your server to latest 1.16.5; if that doesn't solve it, switch from purpur to Paper
