### ISSUE TITLE
Server does not accept new connections

### ISSUE THREAD

**Issue by MedicOP** [Photon-GitHub/AACAdditionPro#48]
Error when starting up:

```java
[10:10:45 INFO]: [AACAdditionPro] Enabling AACAdditionPro v1.6
[10:10:45 WARN]: Exception in thread "Thread-34"
[10:10:45 WARN]: java.lang.ExceptionInInitializerError
[10:10:45 WARN]:        at me.konsolas.iaac.g.run(g.java:45)
[10:10:45 WARN]: Caused by: java.lang.NumberFormatException: For input string: "뻖⫉⁏媟ḭ捾砪ᓤ뤯"
[10:10:45 WARN]:        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[10:10:45 WARN]:        at java.lang.Integer.parseInt(Integer.java:580)
[10:10:45 WARN]:        at java.lang.Integer.parseInt(Integer.java:615)
[10:10:45 WARN]:        at me.konsolas.iaac.rt.<clinit>(Unknown Source)
[10:10:45 WARN]:        ... 1 more
```

Then when players try to log in:
```java
[10:10:57 INFO]: UUID of player JRL05 is 3a6010fc-1ceb-4c56-ab38-effcb28c98dd
[10:10:57 INFO]: Disconnecting com.mojang.authlib.GameProfile@6d4c0ce2[id=3a6010fc-1ceb-4c56-ab38-effcb28c98dd,name=JRL05,properties={textures=[com.mojang.authlib.properties.Property@125746fc]},legacy=false] (/127.0.0.1:51353): Server still starting up
```

**Comment by Photon-GitHub** [comment]
This is an error in aac, therefore I cannot provide help.
